name = "Tectonic Cliftree"
author = "Nyx"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cbf816054bd74ec6da028345a266b9e6a0cbca37631b0e6bad5f96fec37b384"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
